name: CI Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Application
        run: |
          echo "Building Docker Image..."
          docker compose build --no-cache --pull
          working-directory: ./docker/dev

      - name: Start Application
        run: |
          docker compose up -d

      # - name: Run Tests
      #   run: |
      #     echo "Running Tests..."
      #     docker compose exec tw_textforge bash -c "source .venv/bin/activate && pytest -s"
      #     echo "Tests completed!"