name: docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Extract version from pyproject.toml
        id: version
        run: |
          version=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
          echo "tag=$version" >> "$GITHUB_OUTPUT"
          echo "VERSION: $version"

      - name: Build Docker image
        run: |
          cd docker/main
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tw-textforge:latest -t ${{ secrets.DOCKER_USERNAME }}/tw-textforge:${{ steps.version.outputs.tag }} 

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tw-textforge:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tw-textforge:${{ steps.version.outputs.tag }}