name: Publish Python Package

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Build package
        run: uv build
      
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main'
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish